apiVersion: v1
entries:
  waldur:
  - apiVersion: v2
    appVersion: 7.7.0
    created: "2025-09-16T14:47:38.666751848Z"
    dependencies:
    - alias: postgresql
      condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 16.0.1
    - alias: rabbitmq
      condition: rabbitmq.enabled
      name: rabbitmq
      repository: https://charts.bitnami.com/bitnami
      version: 15.0.2
    - alias: postgresqlha
      condition: postgresqlha.enabled
      name: postgresql-ha
      repository: https://charts.bitnami.com/bitnami
      version: 14.2.34
    description: Waldur - Open-Source Cloud Marketplace
    digest: e0274d9169fd6d38e2a609756065a78c85831bd57b12c4463016866ab48b0f77
    home: https://waldur.com
    icon: https://waldur.com/assets/img/icon-bot-01-150x240.png
    keywords:
    - marketplace
    - openstack
    - vmware
    - slurm
    - billing
    maintainers:
    - email: info@opennodecloud.com
      name: OpenNode team
      url: https://opennodecloud.com
    name: waldur
    type: application
    urls:
    - https://ash8m.github.io/waldur-helm/charts/waldur-7.7.0.tgz
    version: 7.7.0
generated: "2025-09-16T14:47:38.640542033Z"
